feat(Radio): add Radio component
landbot-org/lui pull request #15
Opened 2022-11-10 09:09 UTC by EduardoRG

2022-11-10 09:14 UTC, mikelgarciaurbina commented on src/Radio/utils.ts
> +    return theme.palette.neutral[400];
Seems like this line need a test

2022-11-10 10:00 UTC, EduardoRG commented on src/Radio/utils.ts
> +    return theme.palette.neutral[400];
Done!

2022-11-10 15:07 UTC, solilokiam requested changes

2022-11-10 15:07 UTC, solilokiam commented on src/Radio/Radio.styles.ts
> +    box-shadow: 0px 0px 4px rgba(156, 163, 175, 0.5);
Be aware that :focus shadow is different when element is checked.

2022-11-11 08:55 UTC, solilokiam approved these changes

2022-11-11 08:56 UTC, david-gomey approved these changes

2022-11-11 09:06 UTC, merged