Added color prop and extracted size to constants file
landbot-org/lui pull request #27
Opened 2022-12-20 16:14 UTC by SantiMoncada

2022-12-20 16:21 UTC, EduardoRG approved these changes

2022-12-20 16:24 UTC, david-gomey requested changes

2022-12-20 16:24 UTC, david-gomey commented on src/Divider/Divider.styles.ts
> +  height: ${({ $size }) => DIMENSIONS[$size]};
Perhaps we can use pxToRem util

2022-12-20 16:24 UTC, david-gomey commented on src/Divider/Divider.styles.ts
> +  width: ${({ $size }) => DIMENSIONS[$size]};
Perhaps we can use pxToRem util

2022-12-21 07:52 UTC, david-gomey approved these changes

2022-12-21 08:44 UTC, amalv approved these changes

2022-12-21 09:07 UTC, merged